export const COUNTRIES = [
  { code: "KR", flag: "🇰🇷", name: "한국 / South Korea" },
  { code: "US", flag: "🇺🇸", name: "United States" },
  { code: "JP", flag: "🇯🇵", name: "日本 / Japan" },
  { code: "CN", flag: "🇨🇳", name: "中国 / China" },
  { code: "TW", flag: "🇹🇼", name: "台灣 / Taiwan" },
  { code: "HK", flag: "🇭🇰", name: "香港 / Hong Kong" },
  { code: "VN", flag: "🇻🇳", name: "Việt Nam" },
  { code: "TH", flag: "🇹🇭", name: "ประเทศไทย / Thailand" },
  { code: "PH", flag: "🇵🇭", name: "Philippines" },
  { code: "ID", flag: "🇮🇩", name: "Indonesia" },
  { code: "MY", flag: "🇲🇾", name: "Malaysia" },
  { code: "SG", flag: "🇸🇬", name: "Singapore" },
  { code: "MM", flag: "🇲🇲", name: "Myanmar" },
  { code: "KH", flag: "🇰🇭", name: "Cambodia" },
  { code: "MN", flag: "🇲🇳", name: "Монгол / Mongolia" },
  { code: "IN", flag: "🇮🇳", name: "भारत / India" },
  { code: "PK", flag: "🇵🇰", name: "Pakistan" },
  { code: "BD", flag: "🇧🇩", name: "Bangladesh" },
  { code: "NP", flag: "🇳🇵", name: "Nepal" },
  { code: "LK", flag: "🇱🇰", name: "Sri Lanka" },
  { code: "GB", flag: "🇬🇧", name: "United Kingdom" },
  { code: "DE", flag: "🇩🇪", name: "Deutschland / Germany" },
  { code: "FR", flag: "🇫🇷", name: "France" },
  { code: "IT", flag: "🇮🇹", name: "Italia / Italy" },
  { code: "ES", flag: "🇪🇸", name: "España / Spain" },
  { code: "NL", flag: "🇳🇱", name: "Nederland / Netherlands" },
  { code: "BE", flag: "🇧🇪", name: "België / Belgium" },
  { code: "CH", flag: "🇨🇭", name: "Schweiz / Switzerland" },
  { code: "AT", flag: "🇦🇹", name: "Österreich / Austria" },
  { code: "SE", flag: "🇸🇪", name: "Sverige / Sweden" },
  { code: "NO", flag: "🇳🇴", name: "Norge / Norway" },
  { code: "DK", flag: "🇩🇰", name: "Danmark / Denmark" },
  { code: "FI", flag: "🇫🇮", name: "Suomi / Finland" },
  { code: "PL", flag: "🇵🇱", name: "Polska / Poland" },
  { code: "CZ", flag: "🇨🇿", name: "Česko / Czech Republic" },
  { code: "HU", flag: "🇭🇺", name: "Magyarország / Hungary" },
  { code: "RO", flag: "🇷🇴", name: "România / Romania" },
  { code: "RU", flag: "🇷🇺", name: "Россия / Russia" },
  { code: "UA", flag: "🇺🇦", name: "Україна / Ukraine" },
  { code: "TR", flag: "🇹🇷", name: "Türkiye / Turkey" },
  { code: "GR", flag: "🇬🇷", name: "Ελλάδα / Greece" },
  { code: "PT", flag: "🇵🇹", name: "Portugal" },
  { code: "CA", flag: "🇨🇦", name: "Canada" },
  { code: "MX", flag: "🇲🇽", name: "México / Mexico" },
  { code: "BR", flag: "🇧🇷", name: "Brasil / Brazil" },
  { code: "AR", flag: "🇦🇷", name: "Argentina" },
  { code: "CL", flag: "🇨🇱", name: "Chile" },
  { code: "CO", flag: "🇨🇴", name: "Colombia" },
  { code: "PE", flag: "🇵🇪", name: "Perú / Peru" },
  { code: "VE", flag: "🇻🇪", name: "Venezuela" },
  { code: "AU", flag: "🇦🇺", name: "Australia" },
  { code: "NZ", flag: "🇳🇿", name: "New Zealand" },
  { code: "ZA", flag: "🇿🇦", name: "South Africa" },
  { code: "NG", flag: "🇳🇬", name: "Nigeria" },
  { code: "EG", flag: "🇪🇬", name: "مصر / Egypt" },
  { code: "SA", flag: "🇸🇦", name: "المملكة العربية السعودية / Saudi Arabia" },
  { code: "AE", flag: "🇦🇪", name: "الإمارات / UAE" },
  { code: "IL", flag: "🇮🇱", name: "ישראל / Israel" },
  { code: "IR", flag: "🇮🇷", name: "ایران / Iran" },
  { code: "ETC", flag: "🌍", name: "Other / 기타" },
] as const;

export type CountryCode = (typeof COUNTRIES)[number]["code"];

export function getCountry(code: string) {
  return COUNTRIES.find(c => c.code === code);
}
