export const LANGUAGES = [
  { code: "ko", label: "한국어",    flag: "🇰🇷" },
  { code: "en", label: "English",   flag: "🇺🇸" },
  { code: "ja", label: "日本語",    flag: "🇯🇵" },
  { code: "zh", label: "中文",      flag: "🇨🇳" },
  { code: "vi", label: "Tiếng Việt",flag: "🇻🇳" },
  { code: "es", label: "Español",   flag: "🇪🇸" },
  { code: "de", label: "Deutsch",   flag: "🇩🇪" },
  { code: "fr", label: "Français",  flag: "🇫🇷" },
  { code: "hi", label: "हिन्दी",    flag: "🇮🇳" },
  { code: "pt", label: "Português", flag: "🇧🇷" },
] as const;

export type LangCode = typeof LANGUAGES[number]["code"];

export const T = {
  // ── NAV ──────────────────────────────────────────────────────────
  nav_scenarios: { ko:"시나리오", en:"Scenarios", ja:"シナリオ", zh:"场景", vi:"Kịch bản", es:"Escenarios", de:"Szenarien", fr:"Scénarios", hi:"परिदृश्य", pt:"Cenários" },
  nav_howto:     { ko:"이용방법", en:"How to Use", ja:"使い方", zh:"使用方法", vi:"Hướng dẫn", es:"Cómo usar", de:"Anleitung", fr:"Mode d'emploi", hi:"उपयोग विधि", pt:"Como usar" },
  nav_numbers:   { ko:"신고번호", en:"Report Numbers", ja:"通報番号", zh:"举报电话", vi:"Số báo cáo", es:"Números de denuncia", de:"Meldestellen", fr:"Numéros d'urgence", hi:"रिपोर्ट नंबर", pt:"Números de denúncia" },
  nav_stats:     { ko:"📊범죄통계", en:"📊Crime Stats", ja:"📊犯罪統計", zh:"📊犯罪统计", vi:"📊Thống kê tội phạm", es:"📊Estadísticas", de:"📊Kriminalstatistik", fr:"📊Statistiques", hi:"📊अपराध आँकड़े", pt:"📊Estatísticas" },
  nav_partner:   { ko:"🏛️기관도입", en:"🏛️Partnerships", ja:"🏛️機関導入", zh:"🏛️机构合作", vi:"🏛️Hợp tác", es:"🏛️Alianzas", de:"🏛️Partnerschaften", fr:"🏛️Partenariats", hi:"🏛️साझेदारी", pt:"🏛️Parcerias" },
  nav_start:     { ko:"체험시작", en:"Start", ja:"体験開始", zh:"开始体验", vi:"Bắt đầu", es:"Comenzar", de:"Starten", fr:"Commencer", hi:"शुरू करें", pt:"Começar" },

  // ── HERO ─────────────────────────────────────────────────────────
  hero_badge:    { ko:"대한민국 No.1 범죄예방 교육 플랫폼", en:"Korea's #1 Crime Prevention Education Platform", ja:"韓国No.1犯罪予防教育プラットフォーム", zh:"韩国第一犯罪预防教育平台", vi:"Nền tảng giáo dục phòng chống tội phạm số 1 Hàn Quốc", es:"Plataforma #1 de Educación para Prevención del Crimen en Corea", de:"Koreas #1 Verbrechenspräventions-Bildungsplattform", fr:"Plateforme #1 de prévention du crime en Corée", hi:"कोरिया का नंबर 1 अपराध रोकथाम शिक्षा मंच", pt:"Plataforma #1 de Prevenção ao Crime na Coreia" },
  hero_title1:   { ko:"당신도", en:"You Could Be", ja:"あなたも", zh:"你也可能", vi:"Bạn cũng có thể", es:"Tú también podrías", de:"Auch Sie könnten", fr:"Vous aussi pourriez", hi:"आप भी", pt:"Você também pode" },
  hero_title2:   { ko:"속을 수 있습니다", en:"a Victim", ja:"騙される可能性があります", zh:"成为受害者", vi:"trở thành nạn nhân", es:"ser una víctima", de:"Opfer werden", fr:"être victime", hi:"शिकार हो सकते हैं", pt:"ser uma vítima" },
  hero_subtitle: { ko:"실제 범죄 수법을 직접 체험하고, 당하기 전에 먼저 알아두세요.", en:"Experience real crime tactics firsthand — before you become a victim.", ja:"実際の犯罪手口を体験し、被害に遭う前に知っておきましょう。", zh:"亲身体验真实犯罪手法，在受害之前先了解。", vi:"Trải nghiệm thực tế các chiêu lừa đảo — trước khi bạn trở thành nạn nhân.", es:"Experimenta tácticas reales de crimen — antes de convertirte en víctima.", de:"Erleben Sie echte Betrugsmethoden — bevor Sie Opfer werden.", fr:"Découvrez les vraies tactiques criminelles — avant d'en être victime.", hi:"असली अपराध के तरीकों का अनुभव करें — पीड़ित बनने से पहले।", pt:"Experiencie táticas reais de crime — antes de se tornar uma vítima." },
  hero_cta:      { ko:"무료 체험 시작하기", en:"Start Free Experience", ja:"無料体験を始める", zh:"开始免费体验", vi:"Bắt đầu trải nghiệm miễn phí", es:"Comenzar experiencia gratuita", de:"Kostenlos starten", fr:"Démarrer gratuitement", hi:"मुफ़्त अनुभव शुरू करें", pt:"Iniciar experiência gratuita" },
  hero_report:   { ko:"피해신고 안내", en:"Report a Crime", ja:"被害通報案内", zh:"受害举报指南", vi:"Hướng dẫn báo cáo", es:"Guía de denuncia", de:"Verbrechen melden", fr:"Signaler un crime", hi:"अपराध की रिपोर्ट", pt:"Denunciar um crime" },

  // ── STATS SECTION ─────────────────────────────────────────────────
  stats_title:   { ko:"왜 이 프로그램인가", en:"Why This Program?", ja:"なぜこのプログラムか", zh:"为什么需要这个项目", vi:"Tại sao cần chương trình này?", es:"¿Por qué este programa?", de:"Warum dieses Programm?", fr:"Pourquoi ce programme?", hi:"यह प्रोग्राम क्यों?", pt:"Por que este programa?" },
  stats_sub:     { ko:"대한민국 공식 범죄 통계 기반", en:"Based on Official Korean Crime Statistics", ja:"大韓民国公式犯罪統計に基づく", zh:"基于韩国官方犯罪统计", vi:"Dựa trên thống kê tội phạm chính thức của Hàn Quốc", es:"Basado en estadísticas oficiales de crimen de Corea", de:"Basierend auf offiziellen koreanischen Kriminalstatistiken", fr:"Basé sur les statistiques officielles de la criminalité en Corée", hi:"कोरिया के आधिकारिक अपराध आँकड़ों पर आधारित", pt:"Baseado em estatísticas oficiais de crimes da Coreia" },

  // ── SCENARIOS ────────────────────────────────────────────────────
  scenario_voice:    { ko:"보이스피싱", en:"Voice Phishing", ja:"ボイスフィッシング", zh:"电话诈骗", vi:"Lừa đảo qua điện thoại", es:"Phishing telefónico", de:"Telefon-Phishing", fr:"Hameçonnage vocal", hi:"वॉयस फ़िशिंग", pt:"Phishing por voz" },
  scenario_smishing: { ko:"스미싱", en:"Smishing", ja:"スミッシング", zh:"短信诈骗", vi:"Lừa đảo qua tin nhắn", es:"Smishing", de:"SMS-Phishing", fr:"Smishing", hi:"स्मिशिंग", pt:"Smishing" },
  scenario_invest:   { ko:"투자사기", en:"Investment Fraud", ja:"投資詐欺", zh:"投资诈骗", vi:"Lừa đảo đầu tư", es:"Fraude de inversión", de:"Anlagebetrug", fr:"Fraude à l'investissement", hi:"निवेश धोखाधड़ी", pt:"Fraude de investimento" },
  scenario_romance:  { ko:"로맨스스캠", en:"Romance Scam", ja:"ロマンス詐欺", zh:"网恋诈骗", vi:"Lừa đảo tình cảm", es:"Estafa romántica", de:"Romantikbetrug", fr:"Arnaque romantique", hi:"रोमांस स्कैम", pt:"Golpe romântico" },
  scenario_gamble:   { ko:"불법도박", en:"Illegal Gambling", ja:"違法賭博", zh:"非法赌博", vi:"Cờ bạc bất hợp pháp", es:"Juego ilegal", de:"Illegales Glücksspiel", fr:"Jeu illégal", hi:"अवैध जुआ", pt:"Jogo ilegal" },
  scenario_used:     { ko:"중고거래 사기", en:"Used-goods Scam", ja:"中古取引詐欺", zh:"二手交易诈骗", vi:"Lừa đảo mua bán đồ cũ", es:"Estafa de artículos usados", de:"Gebrauchtwarenbetrug", fr:"Arnaque d'occasion", hi:"पुरानी वस्तु धोखाधड़ी", pt:"Golpe de produtos usados" },

  // ── BUTTONS ───────────────────────────────────────────────────────
  btn_experience:  { ko:"체험하기", en:"Experience", ja:"体験する", zh:"开始体验", vi:"Trải nghiệm", es:"Experimentar", de:"Erleben", fr:"Expérimenter", hi:"अनुभव करें", pt:"Experimentar" },
  btn_back:        { ko:"← 메인으로", en:"← Back to Main", ja:"← メインへ", zh:"← 返回主页", vi:"← Về trang chính", es:"← Volver al inicio", de:"← Zurück", fr:"← Retour", hi:"← मुख्य पृष्ठ", pt:"← Voltar" },
  btn_report_now:  { ko:"지금 신고하기", en:"Report Now", ja:"今すぐ通報する", zh:"立即举报", vi:"Báo cáo ngay", es:"Denunciar ahora", de:"Jetzt melden", fr:"Signaler maintenant", hi:"अभी रिपोर्ट करें", pt:"Denunciar agora" },
  btn_start_exp:   { ko:"체험 시작하기", en:"Start Experience", ja:"体験を始める", zh:"开始体验", vi:"Bắt đầu trải nghiệm", es:"Iniciar experiencia", de:"Erfahrung starten", fr:"Démarrer l'expérience", hi:"अनुभव शुरू करें", pt:"Iniciar experiência" },
  btn_guide_use:   { ko:"이용 가이드 보기", en:"View Guide", ja:"利用ガイドを見る", zh:"查看使用指南", vi:"Xem hướng dẫn", es:"Ver guía", de:"Anleitung ansehen", fr:"Voir le guide", hi:"गाइड देखें", pt:"Ver guia" },
  btn_close:       { ko:"닫기", en:"Close", ja:"閉じる", zh:"关闭", vi:"Đóng", es:"Cerrar", de:"Schließen", fr:"Fermer", hi:"बंद करें", pt:"Fechar" },

  // ── POPUP 1 ───────────────────────────────────────────────────────
  popup1_title:  { ko:"범죄예방 체험관에 오신 걸 환영합니다", en:"Welcome to the Crime Prevention Center", ja:"犯罪予防体験館へようこそ", zh:"欢迎来到犯罪预防体验馆", vi:"Chào mừng đến Trung tâm Phòng chống Tội phạm", es:"Bienvenido al Centro de Prevención del Crimen", de:"Willkommen im Verbrechenspräventionszentrum", fr:"Bienvenue au Centre de Prévention du Crime", hi:"अपराध रोकथाम केंद्र में आपका स्वागत है", pt:"Bem-vindo ao Centro de Prevenção ao Crime" },
  popup1_sub:    { ko:"대한민국 모든 시민을 위한 무료 교육 프로그램", en:"Free education program for everyone", ja:"すべての市民のための無料教育プログラム", zh:"面向所有市民的免费教育项目", vi:"Chương trình giáo dục miễn phí cho mọi người", es:"Programa educativo gratuito para todos", de:"Kostenloses Bildungsprogramm für alle", fr:"Programme éducatif gratuit pour tous", hi:"सभी के लिए मुफ़्त शिक्षा कार्यक्रम", pt:"Programa educativo gratuito para todos" },
  popup1_body1:  { ko:"이 프로그램은 범죄를 미리 예방하고, 어린이부터 어르신까지 누구나 이용 가능한 범죄 예방 교육 프로그램입니다.", en:"This program helps prevent crime through education, available for everyone from children to seniors.", ja:"このプログラムは犯罪を事前に予防し、子供から高齢者まで誰でも利用できる犯罪予防教育プログラムです。", zh:"本程序旨在预防犯罪，是面向儿童到老年人所有人群的犯罪预防教育项目。", vi:"Chương trình này giúp phòng ngừa tội phạm thông qua giáo dục, dành cho mọi lứa tuổi.", es:"Este programa ayuda a prevenir el crimen mediante la educación, disponible para todos.", de:"Dieses Programm hilft, Verbrechen durch Bildung zu verhindern, für alle von Kindern bis Senioren.", fr:"Ce programme aide à prévenir le crime par l'éducation, disponible pour tous.", hi:"यह प्रोग्राम शिक्षा के माध्यम से अपराध रोकने में मदद करता है, बच्चों से बुजुर्गों तक सभी के लिए।", pt:"Este programa ajuda a prevenir crimes através da educação, disponível para todos." },
  popup1_body2:  { ko:"혹시 이미 피해를 당하셨거나, 2차 피해가 걱정되어 오셨나요? 어디에 신고해야 할지 막막하신 분들은 아래 버튼을 눌러주세요.", en:"Already a victim or worried about further harm? Not sure where to report? Click below.", ja:"すでに被害を受けた方、または二次被害が心配な方は、下のボタンをクリックしてください。", zh:"已经遭受损失，或担心二次伤害？请点击下方按钮。", vi:"Đã là nạn nhân hoặc lo lắng? Nhấp vào bên dưới.", es:"¿Ya eres víctima o te preocupa sufrir más daños? Haz clic abajo.", de:"Bereits Opfer oder besorgt über weiteren Schaden? Klicken Sie unten.", fr:"Déjà victime ou inquiet d'autres dommages? Cliquez ci-dessous.", hi:"क्या आप पहले से पीड़ित हैं? नीचे क्लिक करें।", pt:"Já é vítima ou preocupado com mais danos? Clique abaixo." },
  popup1_report: { ko:"신고 방법 알아보기", en:"Find Reporting Methods", ja:"通報方法を調べる", zh:"了解举报方法", vi:"Tìm hiểu cách báo cáo", es:"Ver métodos de denuncia", de:"Meldemethoden anzeigen", fr:"Trouver les méthodes de signalement", hi:"रिपोर्टिंग तरीके जानें", pt:"Encontrar métodos de denúncia" },

  // ── POPUP 2 ───────────────────────────────────────────────────────
  popup2_title:  { ko:"이용 가이드", en:"Usage Guide", ja:"利用ガイド", zh:"使用指南", vi:"Hướng dẫn sử dụng", es:"Guía de uso", de:"Nutzungsanleitung", fr:"Guide d'utilisation", hi:"उपयोग गाइड", pt:"Guia de uso" },
  popup2_tab1:   { ko:"부모님용", en:"For Parents", ja:"保護者向け", zh:"家长版", vi:"Dành cho phụ huynh", es:"Para padres", de:"Für Eltern", fr:"Pour les parents", hi:"माता-पिता के लिए", pt:"Para pais" },
  popup2_tab2:   { ko:"자녀교육용", en:"For Children", ja:"子ども教育用", zh:"儿童教育版", vi:"Dành cho trẻ em", es:"Para niños", de:"Für Kinder", fr:"Pour les enfants", hi:"बच्चों के लिए", pt:"Para crianças" },
  popup2_tab3:   { ko:"교육기관용", en:"For Institutions", ja:"教育機関用", zh:"教育机构版", vi:"Dành cho cơ sở giáo dục", es:"Para instituciones", de:"Für Institutionen", fr:"Pour les institutions", hi:"संस्थाओं के लिए", pt:"Para instituições" },

  // ── REPORT PAGE ───────────────────────────────────────────────────
  report_title:     { ko:"2차 피해 예방 · 신고 안내", en:"Reporting Guide & Victim Support", ja:"二次被害防止・通報案内", zh:"举报指南与受害者支持", vi:"Hướng dẫn báo cáo & hỗ trợ nạn nhân", es:"Guía de denuncia y apoyo a víctimas", de:"Meldeleitfaden & Opferhilfe", fr:"Guide de signalement & aide aux victimes", hi:"रिपोर्टिंग गाइड और पीड़ित सहायता", pt:"Guia de denúncia e apoio às vítimas" },
  report_emergency: { ko:"이미 피해를 당하셨나요? 지금 당장 신고하세요.", en:"Already a victim? Report immediately.", ja:"すでに被害を受けましたか？今すぐ通報してください。", zh:"已经受害了吗？立即举报。", vi:"Đã là nạn nhân? Hãy báo cáo ngay.", es:"¿Ya eres víctima? Denuncia de inmediato.", de:"Bereits Opfer? Sofort melden.", fr:"Déjà victime? Signalez immédiatement.", hi:"क्या आप पहले से पीड़ित हैं? अभी रिपोर्ट करें।", pt:"Já é vítima? Denuncie imediatamente." },
  report_faster:    { ko:"신고가 빠를수록 계좌 지급정지로 피해금 환급 가능성이 높아집니다.", en:"The faster you report, the higher the chance of recovering your money.", ja:"早く通報するほど、口座凍結により被害金の回収可能性が高まります。", zh:"举报越快，通过账户冻结追回损失的可能性越高。", vi:"Báo cáo càng nhanh, cơ hội thu hồi tiền càng cao.", es:"Cuanto más rápido denuncies, mayor será la posibilidad de recuperar tu dinero.", de:"Je schneller Sie melden, desto höher die Chance auf Rückerstattung.", fr:"Plus vite vous signalez, plus les chances de récupérer votre argent sont élevées.", hi:"जितनी जल्दी रिपोर्ट करेंगे, पैसे वापस मिलने की संभावना उतनी अधिक।", pt:"Quanto mais rápido denunciar, maior a chance de recuperar seu dinheiro." },
  report_not_fault: { ko:"범죄 피해는 당신의 잘못이 아닙니다.", en:"Being a victim is not your fault.", ja:"犯罪被害はあなたのせいではありません。", zh:"成为受害者不是你的错。", vi:"Trở thành nạn nhân không phải lỗi của bạn.", es:"Ser víctima no es tu culpa.", de:"Opfer zu sein ist nicht Ihre Schuld.", fr:"Être victime n'est pas de votre faute.", hi:"पीड़ित होना आपकी गलती नहीं है।", pt:"Ser vítima não é sua culpa." },
  report_alone:     { ko:"혼자 감당하지 않아도 됩니다", en:"You don't have to face this alone", ja:"一人で抱え込まなくてもいい", zh:"你不必独自承受", vi:"Bạn không phải đối mặt một mình", es:"No tienes que enfrentarlo solo", de:"Sie müssen das nicht alleine tragen", fr:"Vous n'avez pas à faire face à cela seul", hi:"आपको अकेले झेलने की ज़रूरत नहीं", pt:"Você não precisa enfrentar isso sozinho" },

  // ── PRIVACY PAGE ──────────────────────────────────────────────────
  privacy_title:    { ko:"개인정보처리방침 · 이용약관 · 면책조항", en:"Privacy Policy · Terms · Disclaimer", ja:"プライバシーポリシー・利用規約・免責事項", zh:"隐私政策·服务条款·免责声明", vi:"Chính sách bảo mật · Điều khoản · Miễn trách", es:"Política de privacidad · Términos · Descargo", de:"Datenschutz · AGB · Haftungsausschluss", fr:"Confidentialité · CGU · Avertissement", hi:"गोपनीयता नीति · शर्तें · अस्वीकरण", pt:"Privacidade · Termos · Aviso" },
  privacy_summary:  { ko:"한 줄 요약", en:"Summary", ja:"一言要約", zh:"一句话总结", vi:"Tóm tắt", es:"Resumen", de:"Zusammenfassung", fr:"Résumé", hi:"सारांश", pt:"Resumo" },
  privacy_no_collect: { ko:"어떠한 개인 신상정보도 수집하거나 저장하지 않습니다.", en:"We do not collect or store any personal information.", ja:"いかなる個人情報も収集・保存しません。", zh:"我们不收集或存储任何个人信息。", vi:"Chúng tôi không thu thập hoặc lưu trữ bất kỳ thông tin cá nhân nào.", es:"No recopilamos ni almacenamos ninguna información personal.", de:"Wir erheben oder speichern keinerlei persönliche Daten.", fr:"Nous ne collectons ni ne stockons aucune information personnelle.", hi:"हम कोई व्यक्तिगत जानकारी एकत्र या संग्रहीत नहीं करते।", pt:"Não coletamos nem armazenamos nenhuma informação pessoal." },

  // ── PARTNERSHIP PAGE ──────────────────────────────────────────────
  partner_title:   { ko:"기관 도입 안내", en:"Institutional Partnership", ja:"機関導入案内", zh:"机构合作指南", vi:"Hướng dẫn hợp tác tổ chức", es:"Guía de alianzas institucionales", de:"Institutionelle Partnerschaft", fr:"Partenariat institutionnel", hi:"संस्थागत साझेदारी", pt:"Parceria institucional" },
  partner_sub:     { ko:"학교·경찰청·교육청·복지관을 위한 범죄예방 교육 솔루션", en:"Crime prevention education solution for schools, police & welfare centers", ja:"学校・警察署・教育委員会・福祉館のための犯罪予防教育ソリューション", zh:"面向学校、警察局、教育局、福利中心的犯罪预防教育解决方案", vi:"Giải pháp giáo dục phòng chống tội phạm cho trường học, cảnh sát và trung tâm phúc lợi", es:"Solución educativa de prevención del crimen para escuelas, policía y centros de bienestar", de:"Verbrechenspräventions-Bildungslösung für Schulen, Polizei und Sozialzentren", fr:"Solution éducative de prévention du crime pour écoles, police et centres sociaux", hi:"स्कूलों, पुलिस और कल्याण केंद्रों के लिए अपराध रोकथाम शिक्षा समाधान", pt:"Solução educativa de prevenção ao crime para escolas, polícia e centros de bem-estar" },
  partner_contact: { ko:"도입 문의", en:"Contact for Partnership", ja:"導入のお問い合わせ", zh:"合作咨询", vi:"Liên hệ hợp tác", es:"Contacto para alianzas", de:"Partnerschaftsanfrage", fr:"Contact pour partenariat", hi:"साझेदारी के लिए संपर्क", pt:"Contato para parceria" },

  // ── STATS PAGE ────────────────────────────────────────────────────
  stats_page_title: { ko:"대한민국 범죄 통계", en:"Korea Crime Statistics", ja:"韓国犯罪統計", zh:"韩国犯罪统计", vi:"Thống kê tội phạm Hàn Quốc", es:"Estadísticas del crimen en Corea", de:"Kriminalstatistiken Koreas", fr:"Statistiques criminelles de la Corée", hi:"कोरिया अपराध आँकड़े", pt:"Estatísticas de crimes da Coreia" },
  stats_page_sub:   { ko:"경찰청·금감원·통계청 공식 자료 기반", en:"Based on official data from the National Police Agency, FSS & Statistics Korea", ja:"警察庁・金融監督院・統計庁公式資料に基づく", zh:"基于国家警察厅、金融监督院、统计厅官方资料", vi:"Dựa trên dữ liệu chính thức từ Cơ quan Cảnh sát Quốc gia, FSS & Thống kê Hàn Quốc", es:"Basado en datos oficiales de la Agencia Nacional de Policía, FSS y Estadísticas de Corea", de:"Basierend auf offiziellen Daten der Nationalpolizei, FSS & Statistik Korea", fr:"Basé sur les données officielles de la Police Nationale, FSS & Statistiques Corée", hi:"राष्ट्रीय पुलिस एजेंसी, FSS और कोरिया सांख्यिकी के आधिकारिक डेटा पर आधारित", pt:"Baseado em dados oficiais da Polícia Nacional, FSS e Estatísticas da Coreia" },

  // ── FOOTER ────────────────────────────────────────────────────────
  footer_privacy:  { ko:"개인정보처리방침", en:"Privacy Policy", ja:"プライバシーポリシー", zh:"隐私政策", vi:"Chính sách bảo mật", es:"Política de privacidad", de:"Datenschutzrichtlinie", fr:"Politique de confidentialité", hi:"गोपनीयता नीति", pt:"Política de privacidade" },
  footer_terms:    { ko:"이용약관", en:"Terms of Use", ja:"利用規約", zh:"服务条款", vi:"Điều khoản sử dụng", es:"Términos de uso", de:"Nutzungsbedingungen", fr:"Conditions d'utilisation", hi:"उपयोग की शर्तें", pt:"Termos de uso" },
  footer_report:   { ko:"피해신고안내", en:"Report Crime", ja:"被害通報案内", zh:"受害举报", vi:"Báo cáo tội phạm", es:"Denunciar crimen", de:"Verbrechen melden", fr:"Signaler un crime", hi:"अपराध रिपोर्ट करें", pt:"Denunciar crime" },
  footer_contact:  { ko:"기관 문의", en:"Contact", ja:"お問い合わせ", zh:"联系我们", vi:"Liên hệ", es:"Contacto", de:"Kontakt", fr:"Contact", hi:"संपर्क करें", pt:"Contato" },
  footer_rights:   { ko:"All rights reserved.", en:"All rights reserved.", ja:"All rights reserved.", zh:"版权所有。", vi:"Bảo lưu mọi quyền.", es:"Todos los derechos reservados.", de:"Alle Rechte vorbehalten.", fr:"Tous droits réservés.", hi:"सर्वाधिकार सुरक्षित।", pt:"Todos os direitos reservados." },
  footer_edu:      { ko:"교육 목적으로만 사용되며, 실제 범죄 행위를 조장하지 않습니다.", en:"For educational purposes only. Does not promote criminal activity.", ja:"教育目的のみで使用。犯罪行為を助長しません。", zh:"仅供教育目的，不宣扬犯罪行为。", vi:"Chỉ dành cho mục đích giáo dục. Không khuyến khích hành vi tội phạm.", es:"Solo con fines educativos. No promueve actividades criminales.", de:"Nur für Bildungszwecke. Fördert keine kriminellen Aktivitäten.", fr:"À des fins éducatives uniquement. Ne promeut pas les activités criminelles.", hi:"केवल शैक्षिक उद्देश्यों के लिए। आपराधिक गतिविधि को बढ़ावा नहीं देता।", pt:"Apenas para fins educativos. Não promove atividades criminosas." },

  // ── RAINBOW BUTTON ────────────────────────────────────────────────
  rainbow_btn:     { ko:"피해신고\n안내", en:"Report\nCrime", ja:"被害\n通報", zh:"举报\n犯罪", vi:"Báo\ncáo", es:"Denun\nciar", de:"Ver\nmelden", fr:"Signa\nler", hi:"रिपोर्ट\nकरें", pt:"Denun\nciar" },

  // ── GENERAL ───────────────────────────────────────────────────────
  free_badge:      { ko:"무료", en:"FREE", ja:"無料", zh:"免费", vi:"Miễn phí", es:"GRATIS", de:"GRATIS", fr:"GRATUIT", hi:"मुफ़्त", pt:"GRÁTIS" },
  warning:         { ko:"⚠️ 주의", en:"⚠️ Warning", ja:"⚠️ 注意", zh:"⚠️ 注意", vi:"⚠️ Cảnh báo", es:"⚠️ Advertencia", de:"⚠️ Warnung", fr:"⚠️ Avertissement", hi:"⚠️ चेतावनी", pt:"⚠️ Aviso" },
  source:          { ko:"출처", en:"Source", ja:"出典", zh:"来源", vi:"Nguồn", es:"Fuente", de:"Quelle", fr:"Source", hi:"स्रोत", pt:"Fonte" },

  // ── CRIME CENTER PAGE ─────────────────────────────────────────────
  crime_center_title:   { ko:"범죄 예방 센터", en:"Crime Prevention Center", ja:"犯罪予防センター", zh:"犯罪预防中心", vi:"Trung tâm Phòng chống Tội phạm", es:"Centro de Prevención del Crimen", de:"Verbrechenspräventionszentrum", fr:"Centre de Prévention du Crime", hi:"अपराध रोकथाम केंद्र", pt:"Centro de Prevenção ao Crime" },
  crime_free_badge:     { ko:"이 프로그램은 완전 무료입니다", en:"This program is completely free", ja:"このプログラムは完全無料です", zh:"本项目完全免费", vi:"Chương trình này hoàn toàn miễn phí", es:"Este programa es completamente gratuito", de:"Dieses Programm ist völlig kostenlos", fr:"Ce programme est entièrement gratuit", hi:"यह प्रोग्राम पूरी तरह मुफ़्त है", pt:"Este programa é completamente gratuito" },
  crime_free_desc:      { ko:"실제처럼 체험하고 범죄 수법을 미리 알아두세요. 실제 돈은 절대 나가지 않습니다.", en:"Experience real crime tactics — no real money involved, ever.", ja:"実際のように体験し、犯罪手口を事前に知りましょう。実際のお金は一切出ません。", zh:"体验真实犯罪手法——绝不涉及真实金钱。", vi:"Trải nghiệm như thật — không có tiền thật nào liên quan.", es:"Experimenta tácticas reales — nunca se involucra dinero real.", de:"Erleben Sie echte Betrugsmethoden — kein echtes Geld involviert.", fr:"Découvrez les vraies tactiques — aucun vrai argent impliqué.", hi:"असली तरीकों का अनुभव करें — कोई असली पैसा शामिल नहीं।", pt:"Experiencie táticas reais — nenhum dinheiro real envolvido." },
  crime_select_hint:    { ko:"체험할 시나리오를 선택하세요", en:"Select a scenario to experience", ja:"体験するシナリオを選択してください", zh:"请选择要体验的场景", vi:"Chọn kịch bản để trải nghiệm", es:"Selecciona un escenario", de:"Wählen Sie ein Szenario", fr:"Choisissez un scénario", hi:"अनुभव के लिए एक परिदृश्य चुनें", pt:"Selecione um cenário para experimentar" },
  crime_select_title:   { ko:"9가지 범죄 시나리오", en:"9 Crime Scenarios", ja:"9つの犯罪シナリオ", zh:"9种犯罪场景", vi:"9 Kịch bản Tội phạm", es:"9 Escenarios de Crimen", de:"9 Kriminalszenarien", fr:"9 Scénarios de Crime", hi:"9 अपराध परिदृश्य", pt:"9 Cenários de Crime" },
  crime_report_title:   { ko:"피해 신고 및 상담", en:"Report & Consultation", ja:"被害通報・相談", zh:"举报与咨询", vi:"Báo cáo & Tư vấn", es:"Denuncia y Consulta", de:"Meldung & Beratung", fr:"Signalement & Consultation", hi:"रिपोर्ट और परामर्श", pt:"Denúncia e Consultoria" },
  senior_warning:       { ko:"⚠️ 어르신 주의", en:"⚠️ Senior Alert", ja:"⚠️ 高齢者注意", zh:"⚠️ 老年人注意", vi:"⚠️ Cảnh báo người cao tuổi", es:"⚠️ Alerta para mayores", de:"⚠️ Seniorenwarnung", fr:"⚠️ Alerte seniors", hi:"⚠️ वरिष्ठ नागरिक सतर्क रहें", pt:"⚠️ Alerta para idosos" },

  // ── SCENARIO TITLES ───────────────────────────────────────────────
  sc_family_title:      { ko:"가족 사칭 보이스피싱", en:"Family Impersonation", ja:"家族詐称詐欺", zh:"冒充家人诈骗", vi:"Giả mạo gia đình", es:"Suplantación familiar", de:"Familienidentitätsdiebstahl", fr:"Usurpation d'identité familiale", hi:"परिवार की नकल", pt:"Personificação familiar" },
  sc_family_sub:        { ko:"자녀가 급하게 돈을 요구해요", en:"Someone claims to be your child needing money", ja:"子供を装って急にお金を要求", zh:"冒充子女紧急要钱", vi:"Người nào đó giả là con bạn cần tiền", es:"Alguien finge ser tu hijo pidiendo dinero", de:"Jemand gibt vor, Ihr Kind zu sein und Geld zu brauchen", fr:"Quelqu'un prétend être votre enfant et demande de l'argent", hi:"कोई आपके बच्चे का नाटक करके पैसे मांगता है", pt:"Alguém finge ser seu filho pedindo dinheiro" },
  sc_prosecutor_title:  { ko:"검찰·경찰 사칭", en:"Prosecutor Impersonation", ja:"検察・警察詐称", zh:"冒充检察官/警察", vi:"Giả mạo công tố viên", es:"Suplantación de fiscal", de:"Staatsanwalts-Identitätsdiebstahl", fr:"Usurpation de procureur", hi:"अभियोजक की नकल", pt:"Personificação de promotor" },
  sc_prosecutor_sub:    { ko:"내 계좌가 범죄에 연루됐다고 해요", en:"They say your account is linked to a crime", ja:"あなたの口座が犯罪に関与していると言われる", zh:"称您的账户涉及犯罪", vi:"Họ nói tài khoản bạn liên quan đến tội phạm", es:"Dicen que tu cuenta está vinculada a un crimen", de:"Sie sagen, Ihr Konto ist mit einem Verbrechen verbunden", fr:"Ils disent que votre compte est lié à un crime", hi:"वे कहते हैं कि आपका खाता किसी अपराध से जुड़ा है", pt:"Dizem que sua conta está ligada a um crime" },
  sc_romance_title:     { ko:"로맨스 스캠", en:"Romance Scam", ja:"ロマンス詐欺", zh:"网恋诈骗", vi:"Lừa đảo tình cảm", es:"Estafa romántica", de:"Romantikbetrug", fr:"Arnaque romantique", hi:"रोमांस स्कैम", pt:"Golpe romântico" },
  sc_romance_sub:       { ko:"온라인 연인이 돈을 빌려달라고 해요", en:"An online lover asks to borrow money", ja:"オンラインの恋人がお金を借りようとする", zh:"网络恋人要求借钱", vi:"Người yêu online xin mượn tiền", es:"Un amor online pide dinero prestado", de:"Ein Online-Partner bittet um Geld", fr:"Un amour en ligne demande de l'argent", hi:"एक ऑनलाइन प्रेमी पैसे उधार मांगता है", pt:"Um amor online pede dinheiro emprestado" },
  sc_invest_title:      { ko:"투자 사기 (코인·주식)", en:"Investment Fraud", ja:"投資詐欺", zh:"投资诈骗", vi:"Lừa đảo đầu tư", es:"Fraude de inversión", de:"Anlagebetrug", fr:"Fraude à l'investissement", hi:"निवेश धोखाधड़ी", pt:"Fraude de investimento" },
  sc_invest_sub:        { ko:"확실한 수익 보장 투자처를 알고 있대요", en:"They claim to know a guaranteed investment", ja:"確実な収益が保証された投資先を知っていると言う", zh:"声称知道有保证收益的投资渠道", vi:"Họ tuyên bố biết kênh đầu tư đảm bảo lợi nhuận", es:"Dicen conocer una inversión con ganancias garantizadas", de:"Sie behaupten, eine garantierte Investition zu kennen", fr:"Ils prétendent connaître un investissement garanti", hi:"वे दावा करते हैं कि उन्हें गारंटीड निवेश पता है", pt:"Afirmam conhecer um investimento garantido" },
  sc_loan_title:        { ko:"대출 빙자 사기", en:"Loan Fraud", ja:"融資詐欺", zh:"贷款诈骗", vi:"Lừa đảo vay vốn", es:"Fraude de préstamo", de:"Kreditbetrug", fr:"Fraude au prêt", hi:"ऋण धोखाधड़ी", pt:"Fraude de empréstimo" },
  sc_loan_sub:          { ko:"저금리 대출을 해준다고 연락이 왔어요", en:"They offer a low-interest loan out of nowhere", ja:"低金利ローンを提供すると連絡が来た", zh:"突然联系称可提供低息贷款", vi:"Họ liên hệ đề nghị cho vay lãi suất thấp", es:"Ofrecen un préstamo de bajo interés de la nada", de:"Sie bieten ein Darlehen mit niedrigem Zinssatz an", fr:"Ils proposent un prêt à faible taux d'intérêt", hi:"वे कम ब्याज पर ऋण की पेशकश करते हैं", pt:"Oferecem um empréstimo de baixo juro do nada" },
  sc_delivery_title:    { ko:"택배 스미싱", en:"Delivery Smishing", ja:"宅配スミッシング", zh:"快递短信诈骗", vi:"Tin nhắn giả giao hàng", es:"Smishing de entrega", de:"Paket-SMS-Betrug", fr:"Smishing de livraison", hi:"डिलीवरी स्मिशिंग", pt:"Smishing de entrega" },
  sc_delivery_sub:      { ko:"택배 주소 오류로 개인정보를 요구해요", en:"They request personal info due to delivery address error", ja:"配達先住所エラーで個人情報を要求", zh:"以配送地址错误为由索取个人信息", vi:"Họ yêu cầu thông tin cá nhân vì lỗi địa chỉ giao hàng", es:"Piden información personal por error en dirección de entrega", de:"Sie fordern persönliche Daten wegen eines Adressfehlers an", fr:"Ils demandent des données personnelles à cause d'une erreur d'adresse", hi:"डिलीवरी पते की गलती के कारण व्यक्तिगत जानकारी मांगते हैं", pt:"Pedem informações pessoais por erro de endereço" },
  sc_kakao_title:       { ko:"카카오톡 지인 사칭", en:"KakaoTalk Impersonation", ja:"カカオトーク知人詐称", zh:"冒充KakaoTalk联系人", vi:"Giả mạo KakaoTalk", es:"Suplantación en KakaoTalk", de:"KakaoTalk-Identitätsdiebstahl", fr:"Usurpation KakaoTalk", hi:"KakaoTalk पहचान की नकल", pt:"Personificação no KakaoTalk" },
  sc_kakao_sub:         { ko:"친구인 척 급하게 돈을 빌려달라고 해요", en:"Someone pretends to be your friend needing money urgently", ja:"友人を装って急にお金を借りようとする", zh:"冒充朋友紧急借钱", vi:"Ai đó giả làm bạn bè xin mượn tiền gấp", es:"Alguien finge ser tu amigo pidiendo dinero urgente", de:"Jemand gibt vor, Ihr Freund zu sein und dringend Geld zu brauchen", fr:"Quelqu'un prétend être votre ami et demande de l'argent d'urgence", hi:"कोई आपका दोस्त बनकर तुरंत पैसे मांगता है", pt:"Alguém finge ser seu amigo pedindo dinheiro urgente" },
  sc_used_title:        { ko:"중고거래 사기", en:"Used Goods Scam", ja:"中古品取引詐欺", zh:"二手交易诈骗", vi:"Lừa đảo hàng cũ", es:"Estafa de artículos usados", de:"Gebrauchtwarenbetrug", fr:"Arnaque d'occasion", hi:"पुरानी वस्तु घोटाला", pt:"Golpe de artigos usados" },
  sc_used_sub:          { ko:"싸게 판다고 해서 입금했는데 잠수탔어요", en:"Paid for a cheap item, seller disappeared", ja:"安く売るというので入金したが逃げられた", zh:"付款后卖家消失了", vi:"Đã thanh toán xong thì người bán mất tích", es:"Pagué por algo barato y el vendedor desapareció", de:"Bezahlt für einen Artikel, Verkäufer verschwunden", fr:"Payé pour un article, le vendeur a disparu", hi:"सस्ते सामान के लिए पैसे दिए, विक्रेता गायब हो गया", pt:"Pagou por um item barato, o vendedor desapareceu" },
  sc_gambling_title:    { ko:"불법 도박", en:"Illegal Gambling", ja:"違法賭博", zh:"非法赌博", vi:"Cờ bạc bất hợp pháp", es:"Juego ilegal", de:"Illegales Glücksspiel", fr:"Jeu illégal", hi:"अवैध जुआ", pt:"Jogo ilegal" },
  sc_gambling_sub:      { ko:"쉽게 돈을 딸 수 있다고 유혹해요", en:"They lure you with easy money from gambling", ja:"簡単にお金を稼げると誘惑する", zh:"以轻松赚钱为诱饵", vi:"Họ dụ dỗ bạn kiếm tiền dễ dàng", es:"Te atraen con la promesa de dinero fácil", de:"Sie locken mit einfachem Geld durch Glücksspiel", fr:"Ils vous attirent avec de l'argent facile", hi:"जुए से आसान पैसे कमाने का लालच देते हैं", pt:"Atraem você com dinheiro fácil através do jogo" },

  // ── CATEGORY LABELS ───────────────────────────────────────────────
  cat_voice:    { ko:"보이스피싱", en:"Voice Phishing", ja:"ボイスフィッシング", zh:"电话诈骗", vi:"Lừa qua điện thoại", es:"Phishing telefónico", de:"Telefon-Phishing", fr:"Hameçonnage vocal", hi:"वॉयस फ़िशिंग", pt:"Phishing por voz" },
  cat_agency:   { ko:"기관 사칭", en:"Agency Fraud", ja:"機関詐称", zh:"冒充机构", vi:"Giả mạo cơ quan", es:"Fraude de agencia", de:"Behördenbetrug", fr:"Fraude d'agence", hi:"एजेंसी धोखाधड़ी", pt:"Fraude de agência" },
  cat_romance:  { ko:"로맨스 스캠", en:"Romance Scam", ja:"ロマンス詐欺", zh:"网恋诈骗", vi:"Lừa đảo tình cảm", es:"Estafa romántica", de:"Romantikbetrug", fr:"Arnaque romantique", hi:"रोमांस स्कैम", pt:"Golpe romântico" },
  cat_invest:   { ko:"투자 사기", en:"Investment Fraud", ja:"投資詐欺", zh:"投资诈骗", vi:"Lừa đầu tư", es:"Fraude inversión", de:"Anlagebetrug", fr:"Fraude investissement", hi:"निवेश धोखाधड़ी", pt:"Fraude de investimento" },
  cat_loan:     { ko:"대출 사기", en:"Loan Fraud", ja:"融資詐欺", zh:"贷款诈骗", vi:"Lừa vay vốn", es:"Fraude de préstamo", de:"Kreditbetrug", fr:"Fraude de prêt", hi:"ऋण धोखाधड़ी", pt:"Fraude de empréstimo" },
  cat_smishing: { ko:"스미싱", en:"Smishing", ja:"スミッシング", zh:"短信诈骗", vi:"Smishing", es:"Smishing", de:"SMS-Phishing", fr:"Smishing", hi:"स्मिशिंग", pt:"Smishing" },
  cat_messenger:{ ko:"메신저 사기", en:"Messenger Fraud", ja:"メッセンジャー詐欺", zh:"社交软件诈骗", vi:"Lừa qua tin nhắn", es:"Fraude por mensajería", de:"Messenger-Betrug", fr:"Fraude par messagerie", hi:"मैसेंजर धोखाधड़ी", pt:"Fraude por mensagem" },
  cat_used:     { ko:"중고거래 사기", en:"Used Goods Scam", ja:"中古詐欺", zh:"二手诈骗", vi:"Lừa hàng cũ", es:"Estafa usados", de:"Gebrauchtwarenbetrug", fr:"Arnaque d'occasion", hi:"पुरानी वस्तु घोटाला", pt:"Golpe de usados" },
  cat_gambling: { ko:"불법 도박", en:"Illegal Gambling", ja:"違法賭博", zh:"非法赌博", vi:"Cờ bạc bất phép", es:"Juego ilegal", de:"Illegales Glücksspiel", fr:"Jeu illégal", hi:"अवैध जुआ", pt:"Jogo ilegal" },

  // ── SIMULATION PAGE UI ────────────────────────────────────────────
  sim_guide_title:     { ko:"체험 방법", en:"How to Play", ja:"体験方法", zh:"体验方式", vi:"Cách chơi", es:"Cómo jugar", de:"Wie es funktioniert", fr:"Comment jouer", hi:"कैसे खेलें", pt:"Como jogar" },
  sim_guide_1:         { ko:"AI가 실제 사기범처럼 대화를 시작합니다", en:"AI starts talking like a real scammer", ja:"AIが実際の詐欺師のように話しかけてきます", zh:"AI会像真实骗子一样开始对话", vi:"AI bắt đầu trò chuyện như kẻ lừa đảo thật", es:"La IA habla como un estafador real", de:"KI beginnt wie ein echter Betrüger zu sprechen", fr:"L'IA parle comme un vrai arnaqueur", hi:"AI एक असली धोखेबाज की तरह बात करता है", pt:"A IA começa a falar como um golpista real" },
  sim_guide_2:         { ko:"자연스럽게 대화에 응해보세요", en:"Respond naturally to the conversation", ja:"自然に会話に応じてみましょう", zh:"自然地回应对话", vi:"Phản hồi tự nhiên trong cuộc trò chuyện", es:"Responde naturalmente a la conversación", de:"Antworten Sie natürlich auf das Gespräch", fr:"Répondez naturellement à la conversation", hi:"बातचीत में स्वाभाविक रूप से जवाब दें", pt:"Responda naturalmente à conversa" },
  sim_guide_3:         { ko:"송금 요청이 오면 어떻게 할지 선택하세요", en:"Choose what to do when a transfer request comes", ja:"送金要求が来たらどうするか選択してください", zh:"收到转账请求时选择如何应对", vi:"Chọn cách xử lý khi nhận yêu cầu chuyển tiền", es:"Elige qué hacer cuando llegue la solicitud de transferencia", de:"Wählen Sie, was zu tun ist, wenn eine Überweisungsanforderung kommt", fr:"Choisissez quoi faire quand une demande de virement arrive", hi:"जब पैसे भेजने का अनुरोध आए तो क्या करें, चुनें", pt:"Escolha o que fazer quando chegar um pedido de transferência" },
  sim_guide_4:         { ko:"체험 후 범죄 수법과 예방법을 확인하세요", en:"After the experience, review crime tactics and prevention tips", ja:"体験後、犯罪手口と予防法を確認してください", zh:"体验后查看犯罪手法和预防方法", vi:"Sau trải nghiệm, xem lại thủ thuật tội phạm và cách phòng ngừa", es:"Después, revisa las tácticas y consejos de prevención", de:"Nach der Erfahrung, überprüfen Sie Verbrechenstaktiken und Präventionstipps", fr:"Après l'expérience, revoyez les tactiques et conseils de prévention", hi:"अनुभव के बाद, अपराध की तकनीकों और रोकथाम के सुझावों की समीक्षा करें", pt:"Após a experiência, revise as táticas e dicas de prevenção" },
  sim_stats_label:     { ko:"실제 피해 통계", en:"Real Damage Statistics", ja:"実際の被害統計", zh:"真实受害统计", vi:"Thống kê thiệt hại thực tế", es:"Estadísticas de daño real", de:"Echte Schadensstatistiken", fr:"Statistiques de dommages réels", hi:"वास्तविक नुकसान आँकड़े", pt:"Estatísticas de danos reais" },
  sim_safety_notice:   { ko:"실제 돈을 보내거나 외부로 이동하지 마세요. 의심스러우면 즉시 182로 신고하세요.", en:"Do not send real money or go anywhere. If suspicious, report to 182 immediately.", ja:"実際のお金を送ったり外出したりしないでください。不審に思ったら182に通報してください。", zh:"不要转账或外出。如有疑问，请立即拨打182举报。", vi:"Đừng gửi tiền thật hoặc đi đâu. Nếu nghi ngờ, hãy báo 182 ngay.", es:"No envíes dinero real ni salgas. Si sospechas, reporta al 182 de inmediato.", de:"Senden Sie kein echtes Geld. Bei Verdacht sofort 182 anrufen.", fr:"N'envoyez pas d'argent réel. En cas de doute, appelez le 182.", hi:"असली पैसे न भेजें। संदेह हो तो तुरंत 182 पर रिपोर्ट करें।", pt:"Não envie dinheiro real. Em caso de suspeita, ligue imediatamente para o 182." },
  sim_other_scenarios: { ko:"← 다른 시나리오 선택", en:"← Other Scenarios", ja:"← 他のシナリオ", zh:"← 其他场景", vi:"← Kịch bản khác", es:"← Otros escenarios", de:"← Andere Szenarien", fr:"← Autres scénarios", hi:"← अन्य परिदृश्य", pt:"← Outros cenários" },
  sim_danger_detected: { ko:"위험 감지", en:"Risk Detected", ja:"危険検出", zh:"风险检测", vi:"Phát hiện rủi ro", es:"Riesgo detectado", de:"Risiko erkannt", fr:"Risque détecté", hi:"जोखिम पकड़ा गया", pt:"Risco detectado" },
  sim_refuse_btn:      { ko:"🛡️ 돈을 보내지 않겠습니다", en:"🛡️ I will not send money", ja:"🛡️ お金を送りません", zh:"🛡️ 我不会转账", vi:"🛡️ Tôi sẽ không gửi tiền", es:"🛡️ No enviaré dinero", de:"🛡️ Ich werde kein Geld senden", fr:"🛡️ Je n'enverrai pas d'argent", hi:"🛡️ मैं पैसे नहीं भेजूंगा", pt:"🛡️ Não vou enviar dinheiro" },
  sim_input_placeholder: { ko:"메시지를 입력하세요...", en:"Type a message...", ja:"メッセージを入力...", zh:"输入消息...", vi:"Nhập tin nhắn...", es:"Escribe un mensaje...", de:"Nachricht eingeben...", fr:"Écrire un message...", hi:"संदेश लिखें...", pt:"Digite uma mensagem..." },
  sim_sending:         { ko:"전송 중...", en:"Sending...", ja:"送信中...", zh:"发送中...", vi:"Đang gửi...", es:"Enviando...", de:"Senden...", fr:"Envoi...", hi:"भेज रहे हैं...", pt:"Enviando..." },

  // ── EMERGENCY BLOCK ───────────────────────────────────────────────
  em_title:            { ko:"🚨 잠깐, 멈추세요!", en:"🚨 Stop right there!", ja:"🚨 ちょっと待って！", zh:"🚨 请停下！", vi:"🚨 Dừng lại!", es:"🚨 ¡Para ahora mismo!", de:"🚨 Stopp!", fr:"🚨 Arrêtez!", hi:"🚨 रुकिए!", pt:"🚨 Pare agora!" },
  em_leave_title:      { ko:"다른 앱이나 은행으로 이동하려 하세요?", en:"Trying to open a banking app?", ja:"別のアプリや銀行に移動しようとしていますか？", zh:"是否要打开银行或其他应用？", vi:"Bạn đang cố mở ứng dụng ngân hàng?", es:"¿Intentas abrir una app bancaria?", de:"Versuchen Sie, eine Banking-App zu öffnen?", fr:"Essayez-vous d'ouvrir une application bancaire?", hi:"क्या आप कोई बैंकिंग ऐप खोलने की कोशिश कर रहे हैं?", pt:"Tentando abrir um aplicativo bancário?" },
  em_leave_body:       { ko:"지금 화면은 범죄 예방 시뮬레이션입니다.\n실제 은행 앱이나 송금 앱을 열어서\n절대 돈을 보내지 마세요.", en:"This screen is a crime prevention simulation.\nDo NOT open a real banking or payment app\nand send money.", ja:"この画面は犯罪予防シミュレーションです。\n実際の銀行アプリや送金アプリを開いて\nお金を送らないでください。", zh:"当前画面是犯罪预防模拟。\n请勿打开真实银行或支付应用\n进行转账。", vi:"Màn hình này là mô phỏng phòng chống tội phạm.\nĐừng mở ứng dụng ngân hàng thật\nđể gửi tiền.", es:"Esta pantalla es una simulación de prevención del crimen.\nNO abras una app bancaria real\nni envíes dinero.", de:"Dieser Bildschirm ist eine Verbrechenspräventions-Simulation.\nÖffnen Sie KEINE echte Banking-App\nund senden Sie kein Geld.", fr:"Cet écran est une simulation de prévention du crime.\nN'ouvrez PAS une vraie app bancaire\nni n'envoyez d'argent.", hi:"यह स्क्रीन एक अपराध रोकथाम सिमुलेशन है।\nकोई असली बैंकिंग ऐप न खोलें\nऔर पैसे न भेजें।", pt:"Esta tela é uma simulação de prevenção ao crime.\nNÃO abra um app bancário real\nnem envie dinheiro." },
  em_stay_btn:         { ko:"이 앱에 머물기", en:"Stay Here", ja:"このアプリに留まる", zh:"留在此应用", vi:"Ở lại ứng dụng này", es:"Quedarme aquí", de:"Hier bleiben", fr:"Rester ici", hi:"यहाँ रहें", pt:"Ficar aqui" },
  em_continue_btn:     { ko:"계속 체험하기", en:"Continue", ja:"体験を続ける", zh:"继续体验", vi:"Tiếp tục trải nghiệm", es:"Continuar", de:"Fortfahren", fr:"Continuer", hi:"जारी रखें", pt:"Continuar" },
  em_result_btn:       { ko:"교육 결과 보기", en:"View Results", ja:"教育結果を見る", zh:"查看教育结果", vi:"Xem kết quả giáo dục", es:"Ver resultados", de:"Ergebnisse ansehen", fr:"Voir les résultats", hi:"परिणाम देखें", pt:"Ver resultados" },
  em_report_182:       { ko:"이미 돈을 보냈다면 즉시 신고", en:"Already sent money? Report now", ja:"すでにお金を送った場合は即通報", zh:"如已转账请立即举报", vi:"Đã gửi tiền? Báo cáo ngay", es:"¿Ya enviaste dinero? Denuncia ahora", de:"Bereits Geld gesendet? Jetzt melden", fr:"Déjà envoyé de l'argent? Signalez maintenant", hi:"पहले से पैसे भेज दिए? अभी रिपोर्ट करें", pt:"Já enviou dinheiro? Denuncie agora" },

  // ── REVEAL SCREEN ─────────────────────────────────────────────────
  rev_this_is_crime:   { ko:"이것은 범죄입니다", en:"This is a crime", ja:"これは犯罪です", zh:"这是犯罪", vi:"Đây là tội phạm", es:"Esto es un crimen", de:"Das ist ein Verbrechen", fr:"C'est un crime", hi:"यह एक अपराध है", pt:"Isso é um crime" },
  rev_almost_lost:     { ko:"방금 이 금액을 잃을 뻔 했습니다", en:"You almost lost this amount", ja:"今、この金額を失いそうになりました", zh:"您差点损失了这笔钱", vi:"Bạn suýt mất số tiền này", es:"Por poco pierdes esta cantidad", de:"Sie hätten fast diesen Betrag verloren", fr:"Vous avez failli perdre ce montant", hi:"आप लगभग यह राशि खो चुके थे", pt:"Você quase perdeu este valor" },
  rev_safe:            { ko:"실제 돈은 나가지 않았습니다", en:"No real money was sent", ja:"実際のお金は出ていません", zh:"没有真实金钱流失", vi:"Không có tiền thật nào bị mất", es:"No se envió dinero real", de:"Kein echtes Geld wurde gesendet", fr:"Aucun vrai argent n'a été envoyé", hi:"कोई असली पैसा नहीं गया", pt:"Nenhum dinheiro real foi enviado" },
  rev_edu_only:        { ko:"범죄 예방 교육 시뮬레이션입니다", en:"This is a crime prevention education simulation", ja:"犯罪予防教育シミュレーションです", zh:"这是犯罪预防教育模拟", vi:"Đây là mô phỏng giáo dục phòng chống tội phạm", es:"Esta es una simulación educativa de prevención del crimen", de:"Dies ist eine Verbrechenspräventions-Bildungssimulation", fr:"C'est une simulation éducative de prévention du crime", hi:"यह एक अपराध रोकथाम शिक्षा सिमुलेशन है", pt:"Esta é uma simulação educativa de prevenção ao crime" },
  rev_how_to_avoid:    { ko:"✓ 이렇게 예방하세요", en:"✓ How to prevent this", ja:"✓ このように予防しましょう", zh:"✓ 这样预防", vi:"✓ Cách phòng ngừa", es:"✓ Cómo prevenirlo", de:"✓ So können Sie das verhindern", fr:"✓ Comment prévenir cela", hi:"✓ इसे कैसे रोकें", pt:"✓ Como prevenir isso" },
  rev_retry:           { ko:"다시 체험", en:"Try Again", ja:"再体験", zh:"重新体验", vi:"Thử lại", es:"Intentar de nuevo", de:"Nochmal versuchen", fr:"Réessayer", hi:"फिर से कोशिश करें", pt:"Tentar novamente" },
  rev_other:           { ko:"다른 시나리오", en:"Other Scenarios", ja:"他のシナリオ", zh:"其他场景", vi:"Kịch bản khác", es:"Otros escenarios", de:"Andere Szenarien", fr:"Autres scénarios", hi:"अन्य परिदृश्य", pt:"Outros cenários" },

  // ── REPORT LABELS ─────────────────────────────────────────────────
  report_police:  { ko:"경찰청", en:"Police", ja:"警察庁", zh:"警察局", vi:"Cảnh sát", es:"Policía", de:"Polizei", fr:"Police", hi:"पुलिस", pt:"Polícia" },
  report_fss:     { ko:"금융감독원", en:"Financial Supervisory Service", ja:"金融監督院", zh:"金融监督院", vi:"Giám sát tài chính", es:"Supervisión financiera", de:"Finanzaufsicht", fr:"Autorité financière", hi:"वित्तीय पर्यवेक्षण सेवा", pt:"Supervisão financeira" },
  report_kisa:    { ko:"인터넷진흥원", en:"Internet Security Agency", ja:"インターネット振興院", zh:"互联网振兴院", vi:"Cơ quan An ninh mạng", es:"Agencia de Seguridad en Internet", de:"Internet-Sicherheitsbehörde", fr:"Agence de sécurité internet", hi:"इंटरनेट सुरक्षा एजेंसी", pt:"Agência de Segurança na Internet" },
  report_gamble:  { ko:"도박중독 상담", en:"Gambling Helpline", ja:"ギャンブル依存相談", zh:"赌博成瘾咨询", vi:"Đường dây cờ bạc", es:"Línea de juego", de:"Spielsucht-Hotline", fr:"Ligne d'aide jeu", hi:"जुआ सहायता लाइन", pt:"Linha de apoio ao jogo" },

  // ── HOME PAGE ─────────────────────────────────────────────────────
  popup1_start:      { ko:"체험 시작하기 →", en:"Start Experience →", ja:"体験を始める →", zh:"开始体验 →", vi:"Bắt đầu →", es:"Comenzar →", de:"Starten →", fr:"Commencer →", hi:"शुरू करें →", pt:"Começar →" },
  popup2_who:        { ko:"누구와 함께 사용하시나요?", en:"Who are you using this with?", ja:"誰と一緒に使いますか？", zh:"您和谁一起使用？", vi:"Bạn sử dụng với ai?", es:"¿Con quién usas esto?", de:"Mit wem nutzen Sie das?", fr:"Avec qui utilisez-vous cela?", hi:"आप इसे किसके साथ उपयोग कर रहे हैं?", pt:"Com quem você está usando isso?" },
  popup2_guide:      { ko:"상황에 맞는 활용 방법을 안내해 드립니다.", en:"We'll guide you with the right tips for your situation.", ja:"状況に合った活用方法をご案内します。", zh:"我们将为您提供适合您情况的使用建议。", vi:"Chúng tôi sẽ hướng dẫn bạn cách sử dụng phù hợp.", es:"Te guiaremos con los mejores consejos para tu situación.", de:"Wir führen Sie mit den richtigen Tipps für Ihre Situation.", fr:"Nous vous guiderons avec les bons conseils pour votre situation.", hi:"हम आपकी स्थिति के लिए सही सुझाव देंगे।", pt:"Vamos orientá-lo com as dicas certas para sua situação." },
  popup2_go:         { ko:"바로 체험 시작하기 →", en:"Start Now →", ja:"今すぐ体験 →", zh:"立即开始 →", vi:"Bắt đầu ngay →", es:"Empezar ya →", de:"Jetzt starten →", fr:"Commencer maintenant →", hi:"अभी शुरू करें →", pt:"Começar agora →" },
  rainbow_report:    { ko:"2차 피해 예방 신고", en:"Report Crime", ja:"二次被害防止通報", zh:"举报犯罪", vi:"Báo cáo tội phạm", es:"Denunciar crimen", de:"Verbrechen melden", fr:"Signaler un crime", hi:"अपराध रिपोर्ट करें", pt:"Denunciar crime" },
  nav_brand:         { ko:"범죄예방 체험관", en:"Crime Prevention Center", ja:"犯罪予防体験館", zh:"犯罪预防体验馆", vi:"Trung tâm Phòng chống Tội phạm", es:"Centro de Prevención del Crimen", de:"Verbrechenspräventionszentrum", fr:"Centre de Prévention du Crime", hi:"अपराध रोकथाम केंद्र", pt:"Centro de Prevenção ao Crime" },
  nav_edu_badge:     { ko:"교육 목적 전용", en:"Educational Use Only", ja:"教育目的専用", zh:"仅供教育目的", vi:"Chỉ dành cho giáo dục", es:"Solo uso educativo", de:"Nur Bildungszwecke", fr:"Usage éducatif uniquement", hi:"केवल शैक्षिक उद्देश्य", pt:"Somente uso educativo" },
  hero_alert:        { ko:"2025년 피해액 1조원 돌파", en:"2025 losses exceeded ₩1 trillion", ja:"2025年被害額1兆ウォン突破", zh:"2025年损失超过1万亿韩元", vi:"Tổn thất 2025 vượt 1 nghìn tỷ won", es:"Pérdidas 2025 superaron ₩1 billón", de:"Verluste 2025 überstiegen ₩1 Billion", fr:"Pertes 2025 ont dépassé ₩1 billion", hi:"2025 में नुकसान ₩1 खरब से अधिक", pt:"Perdas em 2025 superaram ₩1 trilhão" },
  hero_free_tag:     { ko:"완전 무료", en:"Completely Free", ja:"完全無料", zh:"完全免费", vi:"Hoàn toàn miễn phí", es:"Completamente gratis", de:"Völlig kostenlos", fr:"Entièrement gratuit", hi:"पूरी तरह मुफ़्त", pt:"Completamente gratuito" },
  hero_no_money:     { ko:"실제 돈 없음", en:"No Real Money", ja:"実際のお金なし", zh:"无真实金钱", vi:"Không tiền thật", es:"Sin dinero real", de:"Kein echtes Geld", fr:"Pas de vrai argent", hi:"असली पैसा नहीं", pt:"Sem dinheiro real" },
  hero_edu_tag:      { ko:"교육 전용", en:"Education Only", ja:"教育専用", zh:"仅供教育", vi:"Chỉ giáo dục", es:"Solo educación", de:"Nur Bildung", fr:"Éducation uniquement", hi:"केवल शिक्षा", pt:"Apenas educação" },
  hero_edu_notice:   { ko:"AI가 사기범 역할을 연기하지만 실제 돈은 절대 나가지 않습니다.", en:"The AI plays the role of a scammer, but no real money is ever involved.", ja:"AIが詐欺師の役を演じますが、実際のお金は一切出ません。", zh:"AI扮演骗子角色，但绝不涉及真实金钱。", vi:"AI đóng vai kẻ lừa đảo, nhưng không có tiền thật nào liên quan.", es:"La IA hace de estafador, pero nunca se involucra dinero real.", de:"Die KI spielt die Rolle eines Betrügers, aber kein echtes Geld ist jemals involviert.", fr:"L'IA joue le rôle d'un escroc, mais aucun vrai argent n'est jamais impliqué.", hi:"AI एक धोखेबाज की भूमिका निभाता है, लेकिन कोई असली पैसा शामिल नहीं होता।", pt:"A IA faz o papel de golpista, mas nenhum dinheiro real está envolvido." },
  video_label:       { ko:"홍보 영상", en:"Promotional Video", ja:"PR映像", zh:"宣传视频", vi:"Video giới thiệu", es:"Video promocional", de:"Werbefilm", fr:"Vidéo promotionnelle", hi:"प्रचार वीडियो", pt:"Vídeo promocional" },
  video_title:       { ko:"📺 소개 영상", en:"📺 Introduction Video", ja:"📺 紹介動画", zh:"📺 介绍视频", vi:"📺 Video giới thiệu", es:"📺 Video de introducción", de:"📺 Einführungsvideo", fr:"📺 Vidéo d'introduction", hi:"📺 परिचय वीडियो", pt:"📺 Vídeo de introdução" },
  video_desc:        { ko:"범죄예방 체험관을 영상으로 먼저 확인해보세요", en:"Watch the intro video before you start", ja:"始める前に紹介動画をご覧ください", zh:"开始前先观看介绍视频", vi:"Xem video giới thiệu trước khi bắt đầu", es:"Mira el video introductorio antes de comenzar", de:"Schauen Sie sich das Einführungsvideo an, bevor Sie beginnen", fr:"Regardez la vidéo d'introduction avant de commencer", hi:"शुरू करने से पहले परिचय वीडियो देखें", pt:"Assista ao vídeo de introdução antes de começar" },
  how_title:         { ko:"어떻게 체험하나요?", en:"How Does It Work?", ja:"どうやって体験しますか？", zh:"如何体验？", vi:"Cách trải nghiệm như thế nào?", es:"¿Cómo funciona?", de:"Wie funktioniert es?", fr:"Comment ça fonctionne?", hi:"यह कैसे काम करता है?", pt:"Como funciona?" },
  step1_title:       { ko:"시나리오 선택", en:"Choose a Scenario", ja:"シナリオ選択", zh:"选择场景", vi:"Chọn kịch bản", es:"Elige un escenario", de:"Szenario auswählen", fr:"Choisir un scénario", hi:"एक परिदृश्य चुनें", pt:"Escolha um cenário" },
  step1_desc:        { ko:"보이스피싱, 투자사기, 불법도박 등 9가지 실제 범죄 유형 중 하나를 선택합니다.", en:"Choose from 9 real crime types: voice phishing, investment fraud, illegal gambling, and more.", ja:"ボイスフィッシング、投資詐欺、違法賭博など9種類から選択します。", zh:"从电话诈骗、投资诈骗、非法赌博等9种真实犯罪类型中选择。", vi:"Chọn từ 9 loại tội phạm thực tế.", es:"Elige entre 9 tipos de crimen real.", de:"Wählen Sie aus 9 echten Verbrechenstypen.", fr:"Choisissez parmi 9 types de crimes réels.", hi:"9 वास्तविक अपराध प्रकारों में से एक चुनें।", pt:"Escolha entre 9 tipos reais de crime." },
  step2_title:       { ko:"AI와 대화 체험", en:"Chat with AI Scammer", ja:"AIと会話体験", zh:"与AI骗子对话", vi:"Trò chuyện với AI lừa đảo", es:"Chatea con el estafador IA", de:"Mit KI-Betrüger chatten", fr:"Discuter avec l'arnaqueur IA", hi:"AI धोखेबाज से चैट करें", pt:"Converse com o golpista IA" },
  step2_desc:        { ko:"실제 사기범처럼 행동하는 AI와 대화하며 범죄 수법을 직접 경험합니다. 실제 돈은 나가지 않습니다.", en:"Chat with an AI acting like a real scammer. No real money involved.", ja:"実際の詐欺師のように行動するAIと会話します。実際のお金は出ません。", zh:"与像真实骗子一样行动的AI对话。不涉及真实金钱。", vi:"Trò chuyện với AI như kẻ lừa đảo thật. Không có tiền thật.", es:"Chatea con una IA como estafador real. Sin dinero real.", de:"Chatten Sie mit einer KI wie ein echter Betrüger. Kein echtes Geld.", fr:"Discutez avec une IA comme un vrai escroc. Pas de vrai argent.", hi:"एक असली धोखेबाज जैसी AI से चैट करें। कोई असली पैसा नहीं।", pt:"Converse com uma IA como um golpista real. Sem dinheiro real." },
  step3_title:       { ko:"범죄 수법 확인", en:"Review Crime Tactics", ja:"犯罪手口確認", zh:"查看犯罪手法", vi:"Xem lại thủ thuật tội phạm", es:"Revisa las tácticas criminales", de:"Verbrechenstaktiken überprüfen", fr:"Revoir les tactiques criminelles", hi:"अपराध की तकनीकें देखें", pt:"Revise as táticas criminosas" },
  step3_desc:        { ko:"체험 후 해당 범죄의 수법, 예방법, 신고 번호를 상세히 알려드립니다.", en:"After the experience, we explain the crime tactics, prevention tips, and report numbers in detail.", ja:"体験後、犯罪手口、予防法、通報番号を詳しくお伝えします。", zh:"体验后，我们将详细介绍犯罪手法、预防方法和举报电话。", vi:"Sau trải nghiệm, chúng tôi giải thích chi tiết thủ thuật và cách phòng ngừa.", es:"Tras la experiencia, explicamos las tácticas y números de denuncia.", de:"Nach der Erfahrung erklären wir die Taktiken und Präventions-Tipps.", fr:"Après l'expérience, nous expliquons les tactiques et conseils de prévention.", hi:"अनुभव के बाद, हम अपराध की तकनीकों और रोकथाम के सुझावों को विस्तार से बताते हैं।", pt:"Após a experiência, explicamos as táticas e dicas de prevenção em detalhes." },
  sc_section_title:  { ko:"9가지 범죄 시나리오", en:"9 Crime Scenarios", ja:"9つの犯罪シナリオ", zh:"9种犯罪场景", vi:"9 Kịch bản Tội phạm", es:"9 Escenarios de Crimen", de:"9 Kriminalszenarien", fr:"9 Scénarios de Crime", hi:"9 अपराध परिदृश्य", pt:"9 Cenários de Crime" },
  sc_section_sub:    { ko:"2024–2025년 실제 신고 데이터 기반으로 제작했습니다", en:"Based on 2024–2025 real reported crime data", ja:"2024〜2025年の実際の通報データに基づいて制作", zh:"基于2024-2025年真实报案数据制作", vi:"Được tạo dựa trên dữ liệu tội phạm thực tế 2024–2025", es:"Basado en datos reales de denuncias 2024–2025", de:"Basierend auf echten Verbrechensberichten 2024–2025", fr:"Basé sur des données réelles de signalement 2024–2025", hi:"2024-2025 के वास्तविक रिपोर्ट किए गए अपराध डेटा पर आधारित", pt:"Baseado em dados reais de denúncias 2024–2025" },
  sc_all:            { ko:"전체 목록", en:"All Scenarios", ja:"全リスト", zh:"全部列表", vi:"Tất cả kịch bản", es:"Todos los escenarios", de:"Alle Szenarien", fr:"Tous les scénarios", hi:"सभी परिदृश्य", pt:"Todos os cenários" },
  rpt_section_title: { ko:"피해 즉시 신고하세요", en:"Report Immediately", ja:"被害を即座に通報してください", zh:"立即举报损失", vi:"Báo cáo ngay lập tức", es:"Denuncia de inmediato", de:"Sofort melden", fr:"Signalez immédiatement", hi:"तुरंत रिपोर्ट करें", pt:"Denuncie imediatamente" },
  rpt_section_sub:   { ko:"범죄 피해를 당했거나 의심되면 즉시 전화하세요", en:"Call immediately if you're a victim or suspect a crime", ja:"犯罪被害を受けたり疑いがある場合は即座に電話してください", zh:"如果您遭受犯罪损失或有疑虑，请立即致电", vi:"Gọi ngay nếu bạn là nạn nhân hoặc nghi ngờ có tội phạm", es:"Llama de inmediato si eres víctima o sospechas un crimen", de:"Sofort anrufen wenn Sie Opfer sind oder ein Verbrechen vermuten", fr:"Appelez immédiatement si vous êtes victime ou suspectez un crime", hi:"यदि आप पीड़ित हैं या अपराध का संदेह है तो तुरंत कॉल करें", pt:"Ligue imediatamente se for vítima ou suspeitar de um crime" },
  rpt_police_org:    { ko:"경찰청 신고", en:"Police Report", ja:"警察庁通報", zh:"警察局举报", vi:"Báo cảnh sát", es:"Policía", de:"Polizeimeldung", fr:"Signalement police", hi:"पुलिस रिपोर्ट", pt:"Denúncia policial" },
  rpt_police_desc:   { ko:"즉각 신고·수사", en:"Immediate report & investigation", ja:"即時通報・捜査", zh:"立即举报·调查", vi:"Báo cáo & điều tra ngay", es:"Denuncia inmediata", de:"Sofortige Meldung & Untersuchung", fr:"Signalement & enquête immédiate", hi:"तत्काल रिपोर्ट और जांच", pt:"Denúncia e investigação imediata" },
  rpt_fss_org:       { ko:"금융감독원", en:"Financial Supervisory Service", ja:"金融監督院", zh:"金融监督院", vi:"Giám sát tài chính", es:"Supervisión financiera", de:"Finanzaufsichtsbehörde", fr:"Autorité de surveillance financière", hi:"वित्तीय पर्यवेक्षण सेवा", pt:"Serviço de Supervisão Financeira" },
  rpt_fss_desc:      { ko:"금융 피해 상담", en:"Financial fraud counseling", ja:"金融被害相談", zh:"金融损失咨询", vi:"Tư vấn thiệt hại tài chính", es:"Asesoría de fraude financiero", de:"Beratung bei Finanzbetrug", fr:"Conseil en fraude financière", hi:"वित्तीय धोखाधड़ी परामर्श", pt:"Consultoria sobre fraude financeira" },
  rpt_kisa_org:      { ko:"인터넷진흥원", en:"Internet Security Agency", ja:"インターネット振興院", zh:"互联网振兴院", vi:"Cơ quan An ninh mạng", es:"Agencia de Internet", de:"Internet-Sicherheitsbehörde", fr:"Agence de sécurité internet", hi:"इंटरनेट सुरक्षा एजेंसी", pt:"Agência de Segurança na Internet" },
  rpt_kisa_desc:     { ko:"스미싱·해킹 신고", en:"Smishing & hacking report", ja:"スミッシング・ハッキング通報", zh:"短信诈骗·黑客举报", vi:"Báo smishing & hacking", es:"Denuncia smishing y hacking", de:"Smishing & Hacking melden", fr:"Signalement smishing & piratage", hi:"स्मिशिंग और हैकिंग रिपोर्ट", pt:"Denúncia de smishing e hacking" },
  rpt_gamble_org:    { ko:"도박중독 상담", en:"Gambling Addiction Helpline", ja:"ギャンブル依存相談", zh:"赌博成瘾咨询", vi:"Tư vấn nghiện cờ bạc", es:"Línea de adicción al juego", de:"Spielsucht-Hotline", fr:"Ligne d'aide addiction jeu", hi:"जुआ लत सहायता लाइन", pt:"Linha de ajuda para vício em jogo" },
  rpt_gamble_desc:   { ko:"24시간 무료 상담", en:"24h free counseling", ja:"24時間無料相談", zh:"24小时免费咨询", vi:"Tư vấn miễn phí 24h", es:"Asesoría gratuita 24h", de:"24h kostenlose Beratung", fr:"Conseil gratuit 24h", hi:"24 घंटे मुफ़्त परामर्श", pt:"Aconselhamento gratuito 24h" },
  priv1_title:       { ko:"개인정보 수집 없음", en:"No Personal Data Collected", ja:"個人情報収集なし", zh:"不收集个人信息", vi:"Không thu thập dữ liệu cá nhân", es:"Sin datos personales", de:"Keine persönlichen Daten gesammelt", fr:"Aucune donnée personnelle collectée", hi:"कोई व्यक्तिगत डेटा एकत्र नहीं", pt:"Nenhum dado pessoal coletado" },
  priv1_desc:        { ko:"이름·전화번호·주민번호·계좌번호 등 어떠한 개인 신상정보도 수집하지 않습니다.", en:"We do not collect any personal information including name, phone, ID, or account numbers.", ja:"氏名・電話番号・住民番号・口座番号などいかなる個人情報も収集しません。", zh:"我们不收集任何个人信息，包括姓名、电话、身份证或账号。", vi:"Chúng tôi không thu thập bất kỳ thông tin cá nhân nào.", es:"No recopilamos ninguna información personal.", de:"Wir erheben keine persönlichen Daten wie Name, Telefon, ID oder Kontonummern.", fr:"Nous ne collectons aucune information personnelle comme nom, téléphone ou numéros de compte.", hi:"हम नाम, फ़ोन, आईडी या खाता नंबर सहित कोई व्यक्तिगत जानकारी एकत्र नहीं करते।", pt:"Não coletamos nenhuma informação pessoal como nome, telefone, ID ou números de conta." },
  priv2_title:       { ko:"실제 금전 거래 없음", en:"No Real Financial Transactions", ja:"実際の金銭取引なし", zh:"无真实金融交易", vi:"Không có giao dịch tài chính thật", es:"Sin transacciones financieras reales", de:"Keine echten Finanztransaktionen", fr:"Aucune vraie transaction financière", hi:"कोई वास्तविक वित्तीय लेनदेन नहीं", pt:"Sem transações financeiras reais" },
  priv2_desc:        { ko:"체험 중 표시되는 모든 금액과 계좌는 시뮬레이션입니다. 실제 이체·출금이 발생하지 않습니다.", en:"All amounts and accounts shown are simulations. No real transfers or withdrawals occur.", ja:"体験中に表示される金額や口座はすべてシミュレーションです。実際の送金・出金は発生しません。", zh:"体验中显示的所有金额和账户均为模拟，不会发生真实转账或提款。", vi:"Mọi số tiền và tài khoản hiển thị đều là mô phỏng. Không có giao dịch thật.", es:"Todos los montos y cuentas son simulaciones. No ocurren transferencias reales.", de:"Alle angezeigten Beträge und Konten sind Simulationen. Keine echten Überweisungen.", fr:"Tous les montants et comptes affichés sont des simulations. Aucun vrai transfert.", hi:"सभी प्रदर्शित राशियाँ और खाते सिमुलेशन हैं। कोई असली लेनदेन नहीं होता।", pt:"Todos os valores e contas mostrados são simulações. Sem transferências reais." },
  priv3_title:       { ko:"익명 통계만 수집", en:"Only Anonymous Statistics", ja:"匿名統計のみ収集", zh:"仅收集匿名统计数据", vi:"Chỉ thu thập thống kê ẩn danh", es:"Solo estadísticas anónimas", de:"Nur anonyme Statistiken", fr:"Uniquement des statistiques anonymes", hi:"केवल अज्ञात आँकड़े", pt:"Apenas estatísticas anônimas" },
  priv3_desc:        { ko:"IP를 저장하지 않는 익명 방문 통계만 수집합니다.", en:"We only collect anonymous visit statistics without storing IP addresses.", ja:"IPを保存しない匿名訪問統計のみを収集します。", zh:"仅收集不存储IP地址的匿名访问统计数据。", vi:"Chúng tôi chỉ thu thập thống kê truy cập ẩn danh không lưu IP.", es:"Solo recopilamos estadísticas de visitas anónimas sin guardar IPs.", de:"Wir sammeln nur anonyme Besuchsstatistiken ohne IP-Adressen zu speichern.", fr:"Nous collectons uniquement des statistiques de visite anonymes sans stocker les adresses IP.", hi:"हम IP पते संग्रहीत किए बिना केवल अज्ञात आँकड़े एकत्र करते हैं।", pt:"Coletamos apenas estatísticas de visitas anônimas sem armazenar endereços IP." },
  footer_brand_text: { ko:"범죄예방 체험관 · 교육 목적 전용 · AI Claude 협업 제작", en:"Crime Prevention Center · Educational Use Only · Made with AI Claude", ja:"犯罪予防体験館 · 教育目的専用 · AI Claude協働制作", zh:"犯罪预防体验馆 · 仅供教育目的 · 与AI Claude协作制作", vi:"Trung tâm Phòng chống Tội phạm · Chỉ dành cho giáo dục · Tạo với AI Claude", es:"Centro de Prevención del Crimen · Solo uso educativo · Hecho con AI Claude", de:"Verbrechenspräventionszentrum · Nur Bildungszwecke · Mit AI Claude erstellt", fr:"Centre de Prévention du Crime · Usage éducatif uniquement · Créé avec AI Claude", hi:"अपराध रोकथाम केंद्र · केवल शैक्षिक उपयोग · AI Claude के साथ बनाया", pt:"Centro de Prevenção ao Crime · Somente uso educativo · Feito com AI Claude" },
  footer_disclaimer: { ko:"면책조항", en:"Disclaimer", ja:"免責事項", zh:"免责声明", vi:"Miễn trách nhiệm", es:"Descargo de responsabilidad", de:"Haftungsausschluss", fr:"Avertissement", hi:"अस्वीकरण", pt:"Aviso legal" },
  stat1_lbl:         { ko:"2025년 보이스피싱 피해액", en:"2025 Voice Phishing Losses", ja:"2025年ボイスフィッシング被害額", zh:"2025年电话诈骗损失", vi:"Thiệt hại lừa đảo 2025", es:"Pérdidas por phishing 2025", de:"Telefon-Phishing Verluste 2025", fr:"Pertes hameçonnage vocal 2025", hi:"2025 वॉयस फ़िशिंग नुकसान", pt:"Perdas por phishing de voz 2025" },
  stat2_lbl:         { ko:"연간 피해 신고 건수", en:"Annual Crime Reports", ja:"年間被害通報件数", zh:"年度犯罪举报数量", vi:"Số báo cáo hàng năm", es:"Denuncias anuales", de:"Jährliche Verbrechensberichte", fr:"Rapports de crime annuels", hi:"वार्षिक अपराध रिपोर्ट", pt:"Relatórios anuais de crime" },
  stat3_lbl:         { ko:"1건당 평균 피해액", en:"Avg. Loss per Case", ja:"1件あたり平均被害額", zh:"每案平均损失", vi:"Thiệt hại trung bình mỗi vụ", es:"Pérdida promedio por caso", de:"Durchschnittlicher Verlust pro Fall", fr:"Perte moyenne par cas", hi:"प्रति मामले औसत नुकसान", pt:"Perda média por caso" },
  stat4_lbl:         { ko:"도박 중독 추정 인구", en:"Estimated Gambling Addicts", ja:"ギャンブル依存症推定人口", zh:"估计赌博成瘾人数", vi:"Ước tính người nghiện cờ bạc", es:"Adictos al juego estimados", de:"Geschätzte Spielsüchtige", fr:"Joueurs dépendants estimés", hi:"अनुमानित जुआ व्यसनी", pt:"Viciados em jogo estimados" },
  hero_edu_full:     { ko:"이 플랫폼은 순수 교육 목적입니다. AI가 사기범 역할을 연기하지만 실제 돈은 절대 나가지 않습니다.", en:"This platform is purely for education. The AI plays a scammer, but no real money is ever sent.", ja:"このプラットフォームは純粋に教育目的です。AIが詐欺師の役を演じますが、実際のお金は一切出ません。", zh:"本平台纯粹用于教育目的。AI扮演骗子，但绝不会转出真实金钱。", vi:"Nền tảng này hoàn toàn vì mục đích giáo dục. AI đóng vai kẻ lừa đảo, nhưng không có tiền thật.", es:"Esta plataforma es puramente educativa. La IA hace de estafador, pero nunca se envía dinero real.", de:"Diese Plattform dient rein der Bildung. Die KI spielt einen Betrüger, aber kein echtes Geld wird je gesendet.", fr:"Cette plateforme est purement éducative. L'IA joue un escroc, mais aucun vrai argent n'est envoyé.", hi:"यह मंच पूरी तरह शैक्षिक उद्देश्य के लिए है। AI एक धोखेबाज की भूमिका निभाता है, लेकिन असली पैसे कभी नहीं जाते।", pt:"Esta plataforma é puramente educativa. A IA faz de golpista, mas nenhum dinheiro real é enviado." },

  // ── HALL OF FAME ─────────────────────────────────────────────────
  hof_title:         { ko:"💛 후원자 명예의 전당", en:"💛 Hall of Fame", ja:"💛 殿堂入り後援者", zh:"💛 荣誉殿堂", vi:"💛 Sảnh Danh Vọng", es:"💛 Salón de la Fama", de:"💛 Ruhmeshalle", fr:"💛 Panthéon des donateurs", hi:"💛 नाम की प्रतिष्ठा", pt:"💛 Hall da Fama" },
  hof_sub:           { ko:"이 프로그램을 함께 키워주신 분들입니다", en:"Those who helped grow this program", ja:"このプログラムを一緒に育ててくださった方々です", zh:"感谢这些帮助壮大本项目的朋友们", vi:"Những người đã giúp phát triển chương trình này", es:"Quienes ayudaron a hacer crecer este programa", de:"Diejenigen, die dieses Programm mitgewachsen lassen", fr:"Ceux qui ont aidé à faire grandir ce programme", hi:"वे जिन्होंने इस प्रोग्राम को बढ़ाने में मदद की", pt:"Aqueles que ajudaram a desenvolver este programa" },
  hof_btn_register:  { ko:"💛 명예의 전당에 내 이름 올리기", en:"💛 Add my name to the Hall of Fame", ja:"💛 殿堂に名前を登録する", zh:"💛 将我的名字加入殿堂", vi:"💛 Thêm tên tôi vào Sảnh Danh Vọng", es:"💛 Añadir mi nombre al Salón", de:"💛 Meinen Namen in die Ruhmeshalle eintragen", fr:"💛 Ajouter mon nom au Panthéon", hi:"💛 मेरा नाम जोड़ें", pt:"💛 Adicionar meu nome ao Hall" },
  hof_thanks:        { ko:"💛 후원해 주셔서 감사합니다!", en:"💛 Thank you for your support!", ja:"💛 ご支援ありがとうございます！", zh:"💛 感谢您的支持！", vi:"💛 Cảm ơn bạn đã ủng hộ!", es:"💛 ¡Gracias por tu apoyo!", de:"💛 Danke für Ihre Unterstützung!", fr:"💛 Merci pour votre soutien !", hi:"💛 आपके समर्थन के लिए धन्यवाद!", pt:"💛 Obrigado pelo seu apoio!" },
  hof_placeholder_desc: { ko:"명예의 전당에 올릴 닉네임을 입력해 주세요.\n이름 외 어떤 정보도 수집되지 않습니다.", en:"Enter the nickname to display in the Hall of Fame.\nNo information other than your name is collected.", ja:"殿堂に表示するニックネームを入力してください。\nお名前以外の情報は収集しません。", zh:"请输入显示在殿堂的昵称。\n除姓名外不收集任何信息。", vi:"Nhập biệt danh hiển thị trong Sảnh Danh Vọng.\nKhông thu thập thông tin nào ngoài tên.", es:"Ingresa el apodo para mostrar en el Salón.\nNo se recopila información más allá de tu nombre.", de:"Geben Sie den Spitznamen für die Ruhmeshalle ein.\nAußer dem Namen werden keine Daten gesammelt.", fr:"Entrez le pseudo à afficher dans le Panthéon.\nAucune information autre que votre nom n'est collectée.", hi:"हॉल ऑफ फेम में प्रदर्शित करने के लिए उपनाम दर्ज करें।\nनाम के अलावा कोई जानकारी एकत्र नहीं की जाती।", pt:"Digite o apelido para exibir no Hall da Fama.\nNenhuma informação além do nome é coletada." },
  hof_input_ph:      { ko:"닉네임 입력", en:"Enter nickname", ja:"ニックネームを入力", zh:"输入昵称", vi:"Nhập biệt danh", es:"Ingresa tu apodo", de:"Spitznamen eingeben", fr:"Entrez votre pseudo", hi:"उपनाम दर्ज करें", pt:"Digite o apelido" },
  hof_submit:        { ko:"신청", en:"Submit", ja:"申請", zh:"申请", vi:"Gửi", es:"Enviar", de:"Einreichen", fr:"Soumettre", hi:"सबमिट करें", pt:"Enviar" },
  hof_review_note:   { ko:"운영자 확인 후 명예의 전당에 반영됩니다", en:"Will be added after admin review", ja:"運営者確認後に殿堂に反映されます", zh:"经管理员确认后将添加至殿堂", vi:"Sẽ được thêm sau khi quản trị viên xem xét", es:"Se añadirá tras revisión del administrador", de:"Wird nach Überprüfung durch den Admin hinzugefügt", fr:"Sera ajouté après vérification par l'administrateur", hi:"व्यवस्थापक समीक्षा के बाद जोड़ा जाएगा", pt:"Será adicionado após revisão do administrador" },
  hof_done_title:    { ko:"신청 완료! 곧 명예의 전당에 등재됩니다.", en:"Done! You'll be added to the Hall of Fame soon.", ja:"申請完了！まもなく殿堂入りします。", zh:"申请完成！您即将被载入殿堂。", vi:"Hoàn tất! Bạn sẽ sớm được thêm vào Sảnh Danh Vọng.", es:"¡Listo! Pronto serás añadido al Salón de la Fama.", de:"Erledigt! Sie werden bald in die Ruhmeshalle aufgenommen.", fr:"Terminé ! Vous serez bientôt ajouté au Panthéon.", hi:"हो गया! आप जल्द ही हॉल ऑफ फेम में जोड़े जाएंगे।", pt:"Pronto! Você será adicionado ao Hall da Fama em breve." },
  hof_done_sub:      { ko:"소중한 후원 감사드립니다 💛", en:"Thank you for your precious support 💛", ja:"大切なご支援ありがとうございます 💛", zh:"感谢您宝贵的支持 💛", vi:"Cảm ơn sự ủng hộ quý báu của bạn 💛", es:"Gracias por tu valioso apoyo 💛", de:"Danke für Ihre wertvolle Unterstützung 💛", fr:"Merci pour votre précieux soutien 💛", hi:"आपके मूल्यवान समर्थन के लिए धन्यवाद 💛", pt:"Obrigado pelo seu precioso apoio 💛" },
} as const;

export function t(key: keyof typeof T, lang: LangCode): string {
  return T[key][lang] ?? T[key]["en"] ?? T[key]["ko"];
}

/** 인라인 번역 헬퍼 — 전달한 언어만 있으면 되고, 없으면 en → ko 순 fallback */
export function tl(map: Partial<Record<LangCode, string>>, lang: LangCode): string {
  return map[lang] ?? map["en"] ?? map["ko"] ?? Object.values(map)[0] ?? "";
}
